config/routes.rb
Rails.application.routes.draw do
  root to: "main#index"

  get "up" => "rails/health#show", as: :rails_health_check
  get "/about", to: "about#index"
  get "/register", to: "register#index"
  get "/login", to: "session#index"
  get "/password", to: "password#index"
  get "password/reset", to: "password_reset#index"
  get "password/reset/edit", to: "password_reset#edit"

  patch "/password", to: "password#update"
  patch "password/reset/edit", to: "password_reset#update"

  post "/register", to: "register#create"
  post "/login", to: "session#create"
  post "password/reset", to: "password_reset#create"

  delete "/logout", to: "session#delete"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :user
end

app/models/user.rb
# email:string
# password_digest:string
#
# password:string virtual
# password_confirmation:string virtual

class User < ApplicationRecord
    has_secure_password
    validates :email, presence: true, format: { with: /\A[^@\s]+@[^@\s]+\z/ , message: "Email is not valid" }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_current_user
  def set_current_user
    if session[:user_id]
      Current.user = User.find_by(id: session[:user_id])
    end
  end

  def check_log_in
    if !session[:user_id]
      redirect_to login_path, error: "You must to be logged in first"
    end
  end
end

app/controllers/concerns/about_controller.rb
class AboutController < ApplicationController
    
end

app/controllers/concerns/main_controller.rb
class MainController < ApplicationController
    def index()
        flash[:message] = "Hello User !"
    end
end

app/controllers/concerns/password_controller.rb
class PasswordController < ApplicationController
  before_action :check_log_in
  def index

  end

  def update
    if Current.user.update(password_params)
      redirect_to root_path, notice: "Password Updated !"
    else
      render :index
      return
    end
  end

  private

  def password_params
    params.require(:user).permit(:password, :password_confirmation)
  end
end

app/controllers/concerns/password_reset_controller.rb
class PasswordResetController < ApplicationController
  def index

  end

  def create
    @user = User.find_by(email: params[:email])

    if @user.present?
      PasswordMailer.with(user: @user).reset.deliver_later
      redirect_to root_path, notice: "Email for password reset was sent"
    else
      flash[:error] = "Account with this email address does not exist"
      render :index
    end
  end

  def edit
    @user = User.find_signed!(params[:token], purpose: "password_reset")
  rescue
    redirect_to login_path, notice: "Token expired"
  end

  def update
    @user = User.find_signed!(params[:token], purpose: "password_reset")
    if @user.update(password_params)
      redirect_to root_path, notice: "Password Updated !"
    else
      render :index
      return
    end
  end

  def password_params
    params.require(:user).permit(:password, :password_confirmation)
  end
end

app/controllers/concerns/register_controller.rb
class RegisterController < ApplicationController
  def index
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, notice: "Account Created"
    else
      render :index
    end
  end

  private
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/controllers/concerns/session_controller.rb
class SessionController < ApplicationController
  def index
    @user = User.new
  end

  def create
    user = User.find_by(email: params[:email])
    puts "User found:"
    puts params[:email]
    if user.present? && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path, notice: "Logged In"
    else
      flash[:error] = "Wrong Credentials"
      render :index
    end
  end
  def delete
    session[:user_id] = nil
    redirect_to root_path, notice: "Logged Out"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/about/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ScheduledTweets</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
  </head>

  <body>
    <h1>About Section</h1>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ScheduledTweets</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </head>

  <body>
    <div class="container">
      <%= render partial: "shared/nav" %>
      <%= yield %>
    </div>
  </body>

  <style>
      #regmain h1 {
          margin-top: 5rem;
          margin-bottom: 2rem;
      }

      #regmain form input{
          margin-top : 1rem;
          margin-bottom : 1rem;
      }
  </style>
</html>

app/views/main/index.html.erb
<h1 class="mt-2">Home Page of Scheduled Tweets</h1>
<% if flash[:notice] %>
  <div class="alert alert-primary">
    <label>
      <%= flash[:notice] %>
    </label>
  </div>
<% end %>
<% if Current.user %>
  <h2>Logged in as: <%= Current.user.email %></h2>
<% end %>

app/views/password/index.html.erb
<main id="regmain">
  <h1 class="h1">Change Password</h1>

  <%= form_with model: Current.user, method: :patch, url: password_path do |form| %>

    <% if form.object.errors.any? %>
      <div class="alert alert-danger">
        <% form.object.errors.full_messages.each do |message| %>
          <label>
            <%= message %>
          </label> <br />
        <% end %>
      </div>
    <% end %>


    <%= form.password_field :password, class: "form-control", placeholder: "old password" %>
    <%= form.password_field :password_confirmation, class: "form-control", placeholder: "new password" %>
    <%= form.submit "Create Account", class: "btn btn-primary" %>
  <% end %>

</main>

<style>
    #regmain h1 {
        margin-top: 5rem;
        margin-bottom: 2rem;
    }

    #regmain form input{
        margin-top : 1rem;
        margin-bottom : 1rem;
    }
</style>

app/views/password_reset/edit.html.erb
<main id="regmain">
  <h1 class="h1">Reset Password</h1>

  <% if flash[:error] %>
    <div class="alert alert-danger">
      <label><%= flash[:error] %></label>
    </div>
  <% end %>


  <%= form_with model: @user, method: :patch, url: password_reset_edit_path(token: params[:token]) do |form| %>

    <%= form.password_field :password, class: "form-control", placeholder: "your password" %>
    <%= form.password_field :password_confirmation, class: "form-control", placeholder: "confirm your password" %>
    <%= form.submit "Reset Password", class: "btn btn-primary" %>

  <% end %>

</main>

app/views/password_reset/index.html.erb
<main id="regmain">
  <h1 class="h1">Reset Password</h1>

  <% if flash[:error] %>
    <div class="alert alert-danger">
      <label><%= flash[:error] %></label>
    </div>
  <% end %>


  <%= form_with url: password_reset_path do |form| %>

    <%= form.text_field :email, class: "form-control", placeholder: "test@test.com" %>
    <%= form.submit "Reset Password", class: "btn btn-primary" %>

  <% end %>

</main>

app/views/register/index.html.erb
<main id="regmain">
  <h1 class="h1">Sign Up</h1>

  <%= form_with model: @user, url: register_path do |form| %>

    <% if form.object.errors.any? %>
      <div class="alert alert-danger">
        <% form.object.errors.full_messages.each do |message| %>
          <label>
            <%= message %>
          </label> <br />
        <% end %>
      </div>
    <% end %>

    <%= form.text_field :email, class: "form-control", placeholder: "test@test.com" %>
    <%= form.password_field :password, class: "form-control", placeholder: "password" %>
    <%= form.password_field :password_confirmation, class: "form-control", placeholder: "repeat password" %>
    <%= form.submit "Create Account", class: "btn btn-primary" %>
  <% end %>

</main>

<style>
  #regmain h1 {
      margin-top: 5rem;
      margin-bottom: 2rem;
  }

  #regmain form input{
      margin-top : 1rem;
      margin-bottom : 1rem;
  }
</style>

app/views/session/index.html.erb
<main id="regmain">
  <h1 class="h1">Log In</h1>

  <%= form_with url: login_path do |form| %>

    <% if flash[:error] %>
      <div class="alert alert-danger">
        <label><%= flash[:error] %></label>
      </div>
    <% end %>

    <%= form.text_field :email, class: "form-control", placeholder: "test@test.com" %>
    <%= form.password_field :password, class: "form-control", placeholder: "password" %>
    <%= link_to "Forgot your password ?", "password/reset" %>
    <br />
    <%= form.submit "Log In", class: "btn btn-primary" %>
  <% end %>

</main>

<style>
    #regmain h1 {
        margin-top: 5rem;
        margin-bottom: 2rem;
    }

    #regmain form input{
        margin-top : 1rem;
        margin-bottom : 1rem;
    }
</style>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Scheduled Tweets</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="/">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" href="/about">About</a>
          </li>
          <% if !session[:user_id] %>
            <li class="nav-item">
              <a class="nav-link active" href="/register">Register</a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" href="/login">Log In</a>
            </li>
          <% end %>
          <% if session[:user_id] %>
            <li class="nav-item">
              <%= button_to "Logout", logout_path, method: :delete, class: "nav-link active" %>
            </li>
            <li class="nav-item">
              <%= button_to "Password", password_path, method: :get, class: "nav-link active" %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>